
export global Icons {

    out property <image> gears: @image-url("../../assets/icons/gears.svg");
    out property <image> house: @image-url("../../assets/icons/house.svg");
    out property <image> link: @image-url("../../assets/icons/link.svg");
    out property <image> puzzle-piece: @image-url("../../assets/icons/puzzle-piece.svg");
    out property <image> user: @image-url("../../assets/icons/user.svg");

    out property <image> spotify: @image-url("../../assets/spotify.svg");

}