import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { CatppuccinPallete } from "style/CatppuccinPallete.slint";
import { TextStyles } from "style/TextStyles.slint";
import { Button } from "./kit.slint";
import { Navbar } from "app/components/NavBar.slint";

export component AppWindow inherits Window {
    in-out property<string> page: "loading...";
    in-out property <string> pallete <=> CatppuccinPallete.flavor;
    width: 1000px;
    height: 700px;
    title: "vocer / \{root.page}";

    background: CatppuccinPallete.background;

    animate background {
         duration: 250ms;
    }

    in-out property<int> counter: 0;
    callback request-increase-value();
    VerticalLayout {
        spacing: 20px;
        alignment: start;
        padding-top: 20px;
        width: 1000px;
        height: 700px;
        Navbar {}
    }
}
